// <auto-generated />
using System;
using ApiProcessamento.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiProcessamento.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501002052_AlertaManualNullable")]
    partial class AlertaManualNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("Shared.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeituraSensorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelGravidade")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeituraSensorId");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("Shared.LeituraSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("SensorNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("LeiturasSensor");
                });

            modelBuilder.Entity("Shared.Alerta", b =>
                {
                    b.HasOne("Shared.LeituraSensor", "Leitura")
                        .WithMany()
                        .HasForeignKey("LeituraSensorId");

                    b.Navigation("Leitura");
                });
#pragma warning restore 612, 618
        }
    }
}
