// <auto-generated />
using System;
using ApiProcessamento.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiProcessamento.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("ApiProcessamento.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeituraSensorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelGravidade")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeituraSensorId");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("ApiProcessamento.Models.LeituraSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("SensorNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("LeiturasSensor");
                });

            modelBuilder.Entity("ApiProcessamento.Models.Alerta", b =>
                {
                    b.HasOne("ApiProcessamento.Models.LeituraSensor", "Leitura")
                        .WithMany()
                        .HasForeignKey("LeituraSensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leitura");
                });
#pragma warning restore 612, 618
        }
    }
}
